---
  - name: filebeat setup
    hosts: webservers
    become: true
    tasks:

#    - name: download .deb file
#      command: curl https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-7.4.0-amd64.deb
#    - name: install .deb file
#      command: dpkg -i filebeat-7.4.0-amd64.deb
    - name: download and istall a .deb file
      apt:
        deb: https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-7.4.0-amd64.deb
    - name: copy configuration file from controller to servers
      ansible.builtin.copy:
        src: /etc/ansible/filebeat-config.yml
        dest: /etc/filebeat/filebeat.yml
    - name: enable system on filebeat
      command: filebeat modules enable system
    - name: setup filebeat
      command: filebeat setup
    - name: start the filebeat service
      command: service filebeat start
    - name: start the filebear service on startup
      systemd:
        name: filebeat
        enabled: yes