---
  - name: metricbeat setup
    hosts: webservers
    become: true
    tasks:

#    - name: download .deb file
#      command: curl https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-7.4.0-amd64.deb
#    - name: install .deb file
#      command: dpkg -i filebeat-7.4.0-amd64.deb
    - name: download and istall a .deb file
      apt:
        deb: https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.6.1-amd64.deb
 #       deb: https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.4.0-amd64.deb
    - name: copy configuration file from controller to servers
      ansible.builtin.copy:
        src: /etc/metricbeat/metricbeat.yml
        dest: /etc/metricbeat/metricbeat.yml
    - name: enable docker on metricbeat
      command: metricbeat modules enable docker
    - name: setup metricbeat
      command: metricbeat setup
    - name: start the metricbeat service
      command: service metricbeat start
    - name: start the metricbear service on startup
      systemd:
        name: metricbeat
        enabled: yes